import { useState, useEffect, useRef } from 'react'
import gsap from 'gsap'
import { ScrollTrigger } from 'gsap/ScrollTrigger'
import useDrawingReveal from '../../hooks/useDrawingReveal'

gsap.registerPlugin(ScrollTrigger)

export default function DrawingCard({ imageSrc, index }) {
  const [isRevealed, setIsRevealed] = useState(false)
  const [hasTriggered, setHasTriggered] = useState(false)
  const cardRef = useRef(null)

  const { maskRef, imageRef } = useDrawingReveal(isRevealed, {
    duration: 2,
    direction: index % 2 === 0 ? 'left-to-right' : 'top-to-bottom',
  })

  useEffect(() => {
    if (!cardRef.current) return

    const trigger = ScrollTrigger.create({
      trigger: cardRef.current,
      start: 'top 75%',
      onEnter: () => {
        if (!hasTriggered) {
          setHasTriggered(true)
          setIsRevealed(true)
        }
      },
    })

    return () => {
      trigger.kill()
    }
  }, [hasTriggered])

  return (
    <div className="drawing-card" ref={cardRef}>
      <div className="drawing-card-inner">
        {/* Placeholder state */}
        <div className="card-placeholder">
          <div className="card-placeholder-icon">
            <svg viewBox="0 0 64 64" fill="none" stroke="currentColor" strokeWidth="2">
              <rect x="8" y="8" width="48" height="48" rx="4" />
              <circle cx="24" cy="24" r="6" />
              <path d="M8 44 L24 32 L36 42 L48 28 L56 36" />
            </svg>
          </div>
          <span className="card-placeholder-text">Awaiting reveal...</span>
        </div>

        {/* Revealed image */}
        <div className="card-reveal" ref={maskRef}>
          <img
            ref={imageRef}
            src={imageSrc}
            alt={`AI Generated Artwork ${index + 1}`}
            className="card-image"
            loading="lazy"
          />
        </div>

        {/* Overlay info */}
        <div className="card-overlay">
          <div className="card-badge">Generated by KAYA</div>
        </div>

        {/* Card frame */}
        <div className="card-frame">
          <div className="frame-corner top-left" />
          <div className="frame-corner top-right" />
          <div className="frame-corner bottom-left" />
          <div className="frame-corner bottom-right" />
        </div>
      </div>

      <div className="card-info">
        <span className="card-title">Artwork #{String(index + 1).padStart(3, '0')}</span>
        <span className="card-status">{isRevealed ? 'Revealed' : 'Pending'}</span>
      </div>
    </div>
  )
}
