import { useEffect, useRef } from 'react'
import gsap from 'gsap'
import useDrawingReveal from '../../hooks/useDrawingReveal'
import './DrawingCanvas.css'

export default function DrawingCanvas({ imageSrc, onClose, isActive }) {
  const overlayRef = useRef(null)
  const containerRef = useRef(null)

  const { maskRef, imageRef } = useDrawingReveal(isActive, {
    duration: 3,
    direction: 'left-to-right',
    onComplete: () => {
      // Add a subtle completion effect
      if (containerRef.current) {
        gsap.to(containerRef.current, {
          boxShadow: '0 0 60px rgba(0, 212, 255, 0.4), 0 0 100px rgba(139, 92, 246, 0.2)',
          duration: 0.5,
          yoyo: true,
          repeat: 1,
        })
      }
    },
  })

  useEffect(() => {
    if (overlayRef.current) {
      gsap.fromTo(
        overlayRef.current,
        { opacity: 0 },
        { opacity: 1, duration: 0.3 }
      )
    }
  }, [])

  const handleClose = () => {
    if (overlayRef.current) {
      gsap.to(overlayRef.current, {
        opacity: 0,
        duration: 0.3,
        onComplete: onClose,
      })
    } else {
      onClose()
    }
  }

  return (
    <div className="drawing-overlay" ref={overlayRef} onClick={handleClose}>
      <div
        className="drawing-container"
        ref={containerRef}
        onClick={(e) => e.stopPropagation()}
      >
        <button className="drawing-close" onClick={handleClose} aria-label="Close">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <line x1="18" y1="6" x2="6" y2="18" />
            <line x1="6" y1="6" x2="18" y2="18" />
          </svg>
        </button>

        <div className="drawing-frame">
          <div className="drawing-label">
            <span className="drawing-label-dot" />
            KAYA is creating...
          </div>

          <div className="drawing-canvas-wrapper">
            {/* Background placeholder */}
            <div className="drawing-placeholder">
              <div className="drawing-placeholder-lines">
                {[...Array(5)].map((_, i) => (
                  <div key={i} className="placeholder-line" style={{ animationDelay: `${i * 0.1}s` }} />
                ))}
              </div>
            </div>

            {/* Revealed image */}
            <div className="drawing-reveal" ref={maskRef}>
              <img
                ref={imageRef}
                src={imageSrc}
                alt="AI Generated Artwork"
                className="drawing-image"
              />
            </div>

            {/* Drawing progress line */}
            {isActive && (
              <div className="drawing-progress">
                <div className="drawing-progress-line" />
              </div>
            )}
          </div>

          <div className="drawing-footer">
            <span className="drawing-tag">Generated by KAYA</span>
            <span className="drawing-id">#{Math.floor(Math.random() * 9999).toString().padStart(4, '0')}</span>
          </div>
        </div>
      </div>
    </div>
  )
}
